-- Migration: Create startup_investor_matches Table
-- Description: Creates the table for storing pre-calculated matches between startups and investors
-- Created: 2025-01-09
-- IMPORTANT: Run this migration via Supabase Dashboard SQL Editor

-- Create startup_investor_matches table
CREATE TABLE IF NOT EXISTS startup_investor_matches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Foreign Keys
  startup_id UUID NOT NULL,
  investor_id UUID NOT NULL,
  
  -- Match Quality Metrics
  match_score DECIMAL(5,2) CHECK (match_score >= 0 AND match_score <= 100),
  confidence_level VARCHAR(20) CHECK (confidence_level IN ('high', 'medium', 'low')),
  similarity_score DECIMAL(5,2),
  success_score DECIMAL(5,2),
  
  -- Match Reasoning
  reasoning TEXT, -- Why they were matched (AI explanation)
  why_you_match TEXT[], -- Array of match reasons
  fit_analysis JSONB, -- Detailed fit analysis as JSON
  
  -- Match Status
  status VARCHAR(50) DEFAULT 'suggested' CHECK (status IN (
    'suggested', 
    'viewed', 
    'saved', 
    'contacted', 
    'meeting_scheduled', 
    'rejected',
    'interested',
    'not_interested',
    'funded'
  )),
  
  -- Engagement Tracking
  viewed_at TIMESTAMPTZ,
  intro_requested_at TIMESTAMPTZ,
  contacted_at TIMESTAMPTZ,
  last_interaction TIMESTAMPTZ,
  
  -- Email Content
  intro_email_subject TEXT,
  intro_email_body TEXT,
  
  -- Metadata
  feedback_received BOOLEAN DEFAULT FALSE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_by VARCHAR(50) DEFAULT 'god_algorithm', -- 'god_algorithm', 'ml_model', 'manual', 'rss_discovery'
  algorithm_version VARCHAR(20),
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Prevent duplicate matches
  UNIQUE(startup_id, investor_id),
  
  -- Foreign Key Constraints (add these after table is created if references exist)
  CONSTRAINT fk_startup FOREIGN KEY (startup_id) REFERENCES startup_uploads(id) ON DELETE CASCADE,
  CONSTRAINT fk_investor FOREIGN KEY (investor_id) REFERENCES investors(id) ON DELETE CASCADE
);

-- Create Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_startup_investor_matches_startup_id 
ON startup_investor_matches(startup_id);

CREATE INDEX IF NOT EXISTS idx_startup_investor_matches_investor_id 
ON startup_investor_matches(investor_id);

CREATE INDEX IF NOT EXISTS idx_startup_investor_matches_match_score 
ON startup_investor_matches(match_score DESC NULLS LAST);

CREATE INDEX IF NOT EXISTS idx_startup_investor_matches_status 
ON startup_investor_matches(status) WHERE status = 'suggested';

CREATE INDEX IF NOT EXISTS idx_startup_investor_matches_created_at 
ON startup_investor_matches(created_at DESC);

-- Composite index for common query pattern
CREATE INDEX IF NOT EXISTS idx_startup_investor_matches_status_score 
ON startup_investor_matches(status, match_score DESC NULLS LAST) 
WHERE status = 'suggested';

-- Add comments
COMMENT ON TABLE startup_investor_matches IS 'Stores pre-calculated matches between startups and investors, generated by the queue processor';
COMMENT ON COLUMN startup_investor_matches.match_score IS 'Match score from 0-100, calculated by the matching algorithm';
COMMENT ON COLUMN startup_investor_matches.status IS 'Match status: suggested, viewed, saved, contacted, meeting_scheduled, rejected, funded';
COMMENT ON COLUMN startup_investor_matches.reasoning IS 'Text explanation of why this match was created';
COMMENT ON COLUMN startup_investor_matches.why_you_match IS 'Array of match reasons (e.g., ["industry_match", "stage_match"])';
COMMENT ON COLUMN startup_investor_matches.fit_analysis IS 'Detailed JSON analysis of how well startup and investor fit';

-- Enable Row Level Security (RLS)
ALTER TABLE startup_investor_matches ENABLE ROW LEVEL SECURITY;

-- Allow public read access (for unauthenticated users to view matches)
CREATE POLICY "Allow public read access to matches"
  ON startup_investor_matches FOR SELECT
  USING (true);

-- Allow public insert (for queue processor)
CREATE POLICY "Allow public insert on matches"
  ON startup_investor_matches FOR INSERT
  WITH CHECK (true);

-- Allow public update (for status changes)
CREATE POLICY "Allow public update on matches"
  ON startup_investor_matches FOR UPDATE
  USING (true)
  WITH CHECK (true);

