-- Migration: Create startup_investor_matches Table (SIMPLE VERSION - NO FOREIGN KEYS)
-- Description: Creates the table WITHOUT foreign key constraints to avoid errors
-- Created: 2025-01-09
-- Use this if the v2 version still fails

-- Drop table if exists (uncomment if you want to start fresh)
-- DROP TABLE IF EXISTS startup_investor_matches CASCADE;

-- Create the table (no foreign keys - add them manually later if needed)
CREATE TABLE IF NOT EXISTS startup_investor_matches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Foreign Keys (as UUIDs only, no constraints)
  startup_id UUID NOT NULL,
  investor_id UUID NOT NULL,
  
  -- Match Quality Metrics
  match_score DECIMAL(5,2) CHECK (match_score >= 0 AND match_score <= 100),
  confidence_level VARCHAR(20) CHECK (confidence_level IN ('high', 'medium', 'low')),
  similarity_score DECIMAL(5,2),
  success_score DECIMAL(5,2),
  
  -- Match Reasoning
  reasoning TEXT,
  why_you_match TEXT[],
  fit_analysis JSONB,
  
  -- Match Status
  status VARCHAR(50) DEFAULT 'suggested' CHECK (status IN (
    'suggested', 
    'viewed', 
    'saved', 
    'contacted', 
    'meeting_scheduled', 
    'rejected',
    'interested',
    'not_interested',
    'funded'
  )),
  
  -- Engagement Tracking
  viewed_at TIMESTAMPTZ,
  intro_requested_at TIMESTAMPTZ,
  contacted_at TIMESTAMPTZ,
  last_interaction TIMESTAMPTZ,
  
  -- Email Content
  intro_email_subject TEXT,
  intro_email_body TEXT,
  
  -- Metadata
  feedback_received BOOLEAN DEFAULT FALSE,
  user_id UUID,
  created_by VARCHAR(50) DEFAULT 'god_algorithm',
  algorithm_version VARCHAR(20),
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Prevent duplicate matches
  UNIQUE(startup_id, investor_id)
);

-- Create Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_startup_investor_matches_startup_id 
ON startup_investor_matches(startup_id);

CREATE INDEX IF NOT EXISTS idx_startup_investor_matches_investor_id 
ON startup_investor_matches(investor_id);

CREATE INDEX IF NOT EXISTS idx_startup_investor_matches_match_score 
ON startup_investor_matches(match_score DESC NULLS LAST);

CREATE INDEX IF NOT EXISTS idx_startup_investor_matches_status 
ON startup_investor_matches(status) WHERE status = 'suggested';

CREATE INDEX IF NOT EXISTS idx_startup_investor_matches_created_at 
ON startup_investor_matches(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_startup_investor_matches_status_score 
ON startup_investor_matches(status, match_score DESC NULLS LAST) 
WHERE status = 'suggested';

-- Enable Row Level Security (RLS)
ALTER TABLE startup_investor_matches ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow public read access to matches" ON startup_investor_matches;
DROP POLICY IF EXISTS "Allow public insert on matches" ON startup_investor_matches;
DROP POLICY IF EXISTS "Allow public update on matches" ON startup_investor_matches;

-- Create RLS Policies
CREATE POLICY "Allow public read access to matches"
  ON startup_investor_matches FOR SELECT
  USING (true);

CREATE POLICY "Allow public insert on matches"
  ON startup_investor_matches FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Allow public update on matches"
  ON startup_investor_matches FOR UPDATE
  USING (true)
  WITH CHECK (true);

-- Add comments
COMMENT ON TABLE startup_investor_matches IS 'Stores pre-calculated matches between startups and investors, generated by the queue processor';
COMMENT ON COLUMN startup_investor_matches.match_score IS 'Match score from 0-100, calculated by the matching algorithm';
COMMENT ON COLUMN startup_investor_matches.status IS 'Match status: suggested, viewed, saved, contacted, meeting_scheduled, rejected, funded';

-- Success message
SELECT 'startup_investor_matches table created successfully (without foreign keys)!' as status;
